import { useState } from 'react'
import './ResolutionPanel.css'

function ResolutionPanel({ resolution, onClose }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(resolution.codePatch || resolution.proposedFix || '')
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (!resolution) return null

  return (
    <div className="resolution-overlay" onClick={onClose}>
      <div className="resolution-panel" onClick={(e) => e.stopPropagation()}>
        <div className="resolution-header">
          <div>
            <h3>🔧 Proposed Fix</h3>
            {resolution.generatedBy && (
              <p className="generated-by">Generated by {resolution.generatedBy}</p>
            )}
          </div>
          <button className="close-btn" onClick={onClose}>✕</button>
        </div>

        {resolution.explanation && (
          <div className="resolution-explanation">
            <strong>Explanation:</strong>
            <p>{resolution.explanation}</p>
          </div>
        )}

        <div className="resolution-code">
          <div className="code-header">
            <span className="code-language">
              {resolution.language || 'Code'}
            </span>
            <button 
              className={`copy-btn ${copied ? 'copied' : ''}`}
              onClick={handleCopy}
            >
              {copied ? '✓ Copied!' : '📋 Copy'}
            </button>
          </div>
          <pre className="code-block">
            <code>{resolution.codePatch || resolution.proposedFix || 'No code patch available'}</code>
          </pre>
        </div>

        {resolution.timestamp && (
          <div className="resolution-footer">
            Generated: {new Date(resolution.timestamp).toLocaleString()}
          </div>
        )}
      </div>
    </div>
  )
}

export default ResolutionPanel
