import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'resolution',
  title: 'Resolution',
  type: 'document',
  fields: [
    defineField({
      name: 'resolutionId',
      title: 'Resolution ID',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'incidentId',
      title: 'Incident ID',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'codePatch',
      title: 'Code Patch',
      type: 'text',
    }),
    defineField({
      name: 'language',
      title: 'Programming Language',
      type: 'string',
    }),
    defineField({
      name: 'explanation',
      title: 'Explanation',
      type: 'text',
    }),
    defineField({
      name: 'generatedBy',
      title: 'Generated By',
      type: 'string',
    }),
    defineField({
      name: 'timestamp',
      title: 'Timestamp',
      type: 'datetime',
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    select: {
      title: 'incidentId',
      language: 'language',
      generatedBy: 'generatedBy',
    },
    prepare(selection) {
      const {title, language, generatedBy} = selection
      return {
        title: `Fix for ${title}`,
        subtitle: `${language || 'Unknown'} - by ${generatedBy || 'Unknown'}`,
      }
    },
  },
})
